### ISSUE TITLE
Adding a section on software for hackathons

### ISSUE THREAD

**Issue by anishathalye** [MLH/hackathon-organizer-guide#38]
I talked to @Shy about adding a section on open-source software that hackathons have built for their event (as a follow-up from my [Hackcon talk](http://www.anish.io/hackcon4)).

Though, currently, the guide is organized in terms of an organizer timeline. Where would a page on software for hackathons fit in?

**Comment by bih** [comment]
Hey Anish!

Fantastic talk! Looks like it went well at Hackcon. Regarding adding open-source software to the guide, I think it would belong in [4 Months Before](https://github.com/MLH/hackathon-organizer-guide/tree/master/Organizer-Timeline/4-Months-Before) because that's roughly when you'd want to consider thinking about and developing/using software during the organising timeline for a hackathon.

What do you think?

**Comment by theycallmeswift** [comment]
Maybe we should add a section called "Organizer Tools"?  We could create a software page, vendors page, etc.

**Comment by Shy** [comment]
Organizer tools sounds great. I'll create that shortly.

**Comment by anishathalye** [comment]
Bump

**Comment by anishathalye** [comment]
Bump

**Comment by theycallmeswift** [comment]
@Shy can you give @anishathalye a status update on this?

**Comment by anishathalye** [comment]
By the way, @cconsidine has already worked on compiling a list of software for hackathons: https://github.com/cconsidine/awesome-hackathons

**Comment by Shy** [comment]
Hey @anishathalye Sorry about the delay on this. Things have been a little busy with Prime and Hackathon Season 2017 coming up. 

I've got time blocked out for myself on thursday to draft a page so it'll be done before EOD then.

**Comment by Shy** [comment]
@anishathalye I've added a short software section - https://github.com/MLH/hackathon-organizer-guide/commit/6d96cb791de6afea1f967129369e00fc55a8d727

Feel free to add to it.
