### ISSUE TITLE
License

### ISSUE THREAD

**Issue by anishathalye** [MLH/hackathon-organizer-guide#39]
This repository doesn't mention any explicit license for the content.

Is there any chance that this content can be released under a copyleft license, such as [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)?

**Comment by bih** [comment]
You're right, we haven't thought about the licence that much but it's definitely important going forward. I don't see any reason why we wouldn't want to use the CC-BY-SA 4.0 license for the Guide.

I'll throw this idea up with our team today. Thanks for raising this, @anishathalye!

**Comment by anishathalye** [comment]
@bih what was the response?

**Comment by theycallmeswift** [comment]
Sorry for the delay.  I would like us to go with [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).  

I've found that copyleft can actually be more restrictive than open for a lot of people, especially people who are advocating for hackathons in a corporate setting.  There are a lot of places where you literally cannot use or share anything with a copyleft license at all internally (I've worked some of these places).  Since the guide is meant to help as many people as possible, I believe we should use the license that enables the maximum audience to use it.  Attribution should cover giving the original work credit.

@anishathalye is there a specific reason you want to see copyleft?

**Comment by anishathalye** [comment]
CC BY 4.0 in a way is even [better](https://creativecommons.org/share-your-work/public-domain/freeworks/), so I'd be happy with that.

**Comment by theycallmeswift** [comment]
Great.  @bih is on it then.

**Comment by anishathalye** [comment]
Awesome. Glad to see that this change is being made 👍

**Comment by theycallmeswift** [comment]
NP.  Thanks for contributing!

**Comment by bih** [comment]
We're all good! https://github.com/MLH/hackathon-organizer-guide/commit/d82e61ed979c212ef8d7be9bd41e9161b8451a75

+ What Swift said 👍
